# FROM ghcr.io/cirruslabs/flutter:stable AS build
# WORKDIR /app

# COPY pubspec.yaml .
# COPY pubspec.lock .
# RUN flutter pub get

# COPY . .
# RUN flutter config --enable-web
# RUN flutter build web

# FROM nginx:alpine
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/build/web /usr/share/nginx/html

# EXPOSE 80

FROM ghcr.io/cirruslabs/flutter:stable AS build
WORKDIR /app

COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get

COPY . .
RUN flutter config --enable-web
RUN flutter build web

FROM nginxinc/nginx-unprivileged:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 8080